name: 'My Event'
description: 'イベントのコンテンツタイプを追加する Drupal recipe サンプル'
type: 'Content type'

install:
  - datetime_range
  - field
  - field_group
  - field_ui
  - menu_ui
  - node
  - path
  - text

config:
  actions:
    user.role.editor:
      ensure_exists:
        label: 'イベント編集者'
      grantPermissions:
        - 'delete any event content'
        - 'edit any event content'
